apiVersion: v1
kind: Service
metadata:
  name: client-pod-service
spec:
  type: NodePort
  ports:
    - port: 3050
      targetPort: 80
      nodePort: 31131
  selector:
    component: front


# apiVersion: v1
# kind: Service
# metadata:
#   name: client-pod-service
# spec:
#   type: NodePort
#   ports:
#     - port: 3050
#       targetPort: 80
#       NodePort: 44044
#   selector:
#     component: front